### ISSUE TITLE
I18n checklist: language

### ISSUE THREAD

**Issue by fsteeg** [reconciliation-api/specs#125]
This is a self-review checklist based on the <a href="https://www.w3.org/TR/international-specs/#language_checklist">Internationalization Best Practices for Spec Developers</a>.

(All lines seemed relevant for us here, I suggest we ~~strikeout~~ things that turn out not to be.)

See also issue #52, PR #108 and notes at https://etherpad.lobid.org/p/reconciliation-i18n.

Check marks indicate requirements that are fulfilled by this spec. Add comments to describe conformance.

### Language basics
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It should be possible to associate a language with any piece of <a data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#dfn-localizable-text">localizable text</a> or <a data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#dfn-natural-language">natural language</a> content. <a href="https://www.w3.org/TR/international-specs/#lang_basics_1" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Where possible, there should  be a way to label <a data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#dfn-natural-language">natural language</a> changes in inline text. <a href="https://www.w3.org/TR/international-specs/#lang_basics_inline" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Consider whether it is useful to express the <a href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta">intended linguistic audience</a> of a resource, in addition to specifying the language used for <a href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">text processing</a>. <a href="https://www.w3.org/TR/international-specs/#lang_basics_meta" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> A language declaration that indicates the <a data-link-type="dfn" data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#dfn-text-processing-language">text-processing language</a> for a range of text must associate  a single language  value with a specific range of text. <a href="https://www.w3.org/TR/international-specs/#tp_lang_values" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Use the HTML <code class="kw" translate="no">lang</code> and XML <code class="kw" translate="no">xml:lang</code> language attributes where appropriate to identify the <a href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">text processing language</a>, rather than creating a new attribute or mechanism. <a href="https://www.w3.org/TR/international-specs/#lang_attribute_xml" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It should be possible to associate a  metadata-type language declaration (which indicates the intended use of the resource rather than the language of a specific range of text)  with multiple language  values. <a href="https://www.w3.org/TR/international-specs/#metadata_lang_values" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Attributes that express the language of external resources should not use the HTML <code class="kw" translate="no">lang</code> and XML <code class="kw" translate="no">xml:lang</code> language attributes, but should use a different attribute when they represent metadata (which indicates the intended use of the resource rather than the language of a specific range of text). <a href="https://www.w3.org/TR/international-specs/#metadata_not_lang" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Defining language values
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Values for language declarations must use BCP 47. <a href="https://www.w3.org/TR/international-specs/#lang_use_bcp47" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Refer to BCP 47, not to its constituent parts, such as RFC 5646 or RFC 4647. <a href="https://www.w3.org/TR/international-specs/#lang_bcp_not_rfc" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Be specific about what level of conformance you expect for language tags: BCP 47 defines two levels of conformance, "valid" and "well-formed". <a href="https://www.w3.org/TR/international-specs/#lang_values_specificity" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Specifications may require implementations to check if language tags are "valid", but in most circumstances should only require that the language tags be "well-formed". <a href="https://www.w3.org/TR/international-specs/#lang_checking_well_formed" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Specifications should require content and content authors to use "valid" language tags. <a href="https://www.w3.org/TR/international-specs/#lang_values_valid" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Specifications <em class="rfc2119">SHOULD</em> refer to the IANA Language Subtag Registry instead of providing lists of codes extracted from ISO 639, ISO 3166, or other standards. <a href="https://www.w3.org/TR/international-specs/#use_lstr" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Avoid creating a list of valid or supported language tags, language subtags, or <a data-link-type="dfn" data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#dfn-locale">locales</a>. <a href="https://www.w3.org/TR/international-specs/#avoid_lang_lists" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Declaring  language
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> The specification should indicate how to define the default text-processing language for the resource as a whole. <a href="https://www.w3.org/TR/international-specs/#lang_whole_res" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Content within the resource should inherit the language of the text-processing declared at the resource level, unless it is specifically overridden. <a href="https://www.w3.org/TR/international-specs/#lang_inherit" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Consider whether it is necessary to have separate declarations to indicate the text-processing language versus metadata about the expected use of the resource. <a href="https://www.w3.org/TR/international-specs/#lang_tp_meta" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> If there is only one language declaration for a resource, and it has more than one language tag as a value, it must be possible to identify the default text-processing language for the resource. <a href="https://www.w3.org/TR/international-specs/#lang_mixing" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> By default, blocks of content should inherit any text-processing language set for the resource as a whole. <a href="https://www.w3.org/TR/international-specs/#lang_block_inherit" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It should be possible to indicate a change in language for blocks of content where the language changes. <a href="https://www.w3.org/TR/international-specs/#lang_block_change" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It should be possible to indicate language for spans of inline text where the language changes. <a href="https://www.w3.org/TR/international-specs/#lang_inline_spans" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Detecting & matching language
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Reference BCP47 for language tag matching. <a href="https://www.w3.org/TR/international-specs/#lang_matching_bcp" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
