### ISSUE TITLE
I18n checklist: text direction

### ISSUE THREAD

**Issue by fsteeg** [reconciliation-api/specs#126]
This is a self-review checklist based on the <a href="https://www.w3.org/TR/international-specs/#text_direction_checklist">Internationalization Best Practices for Spec Developers</a>.

(I've skipped what seemed formatting and markup related here.)

See also issue #52, #125 and notes at https://etherpad.lobid.org/p/reconciliation-i18n.

### Basic requirements
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It must be possible to indicate base direction for each individual paragraph-level item of <a data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#dfn-natural-language">natural language</a> text that will be read by someone. <a href="https://www.w3.org/TR/international-specs/#dir_paragraphs" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It must be possible to indicate base direction changes for embedded runs of inline bidirectional text for all <a data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#dfn-localizable-text">localizable text</a>. <a href="https://www.w3.org/TR/international-specs/#dir_inline" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Background information
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Do not assume that direction can be determined from language information. <a href="https://www.w3.org/TR/international-specs/#bidi_lang" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Base direction values
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Values for the default base direction should include left-to-right, right-to-left, and auto. <a href="https://www.w3.org/TR/international-specs/#bidi_values_req" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Handling direction in markup
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> The spec should  indicate how to define a default base direction for the resource as a whole, ie. set the overall base direction. <a href="https://www.w3.org/TR/international-specs/#bidi_whole_res" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> The  default base direction, in the absence of other information, should be LTR. <a href="https://www.w3.org/TR/international-specs/#bidi_res_default" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> The content author must be able to indicate parts of the text where the base direction changes. At the block level, this should be achieved using attributes or metadata, and should not rely on Unicode control characters. <a href="https://www.w3.org/TR/international-specs/#bidi_block_change" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It must be possible to also set the direction for content fragments to <code class="kw" translate="no">auto</code>. This means that the base direction will be determined by examining the content itself. <a href="https://www.w3.org/TR/international-specs/#bidi_block_auto" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> If the overall base direction is set to <code class="kw" translate="no">auto</code> for plain text, the direction of content paragraphs should be determined on a paragraph by paragraph basis. <a href="https://www.w3.org/TR/international-specs/#bidi_block_para" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Handling base direction for strings
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Provide metadata constructs that can be used to indicate the base direction of any <a data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#dfn-natural-language">natural language</a> string. <a href="https://www.w3.org/TR/international-specs/#bidi_strings_metadata" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Specify that consumers of strings should use  heuristics, preferably based on the Unicode Standard first-strong algorithm, to detect the base direction of a string except where metadata is provided. <a href="https://www.w3.org/TR/international-specs/#bidi_strings_heuristics" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Where possible, define a field to  indicate the default direction for all strings in a given resource or document. <a href="https://www.w3.org/TR/international-specs/#bidi_strings_default" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Do NOT assume that a creating a document-level default without the ability to change direction for any string is sufficient. <a href="https://www.w3.org/TR/international-specs/#bidi_strings_metadata_and_default" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> If metadata is not available due to legacy implementations and cannot otherwise be provided, specifications <em class="rfc2119">MAY</em> allow a base direction to be interpolated from available language metadata. <a href="https://www.w3.org/TR/international-specs/#bidi_strings_script_tag" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Specifications <em class="rfc2119">MUST NOT</em> require the production or use of paired bidi controls. <a href="https://www.w3.org/TR/international-specs/#bidi_strings_paired_controls" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Setting base direction for inline or substring text
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It must be possible to indicate spans of inline text where the base direction changes. If markup is available, this is the preferred method. Otherwise your specification must require that Unicode control characters are recognized by the receiving application, and correctly implemented. <a href="https://www.w3.org/TR/international-specs/#bidi_inline_change" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It must be possible to also set the direction for a span of inline text to <code class="kw" translate="no">auto</code>, which means that the base direction will be determined by examining the content itself. A typical approach here would be to set the direction based on the first strong directional character outside of any markup. <a href="https://www.w3.org/TR/international-specs/#bidi_inline_auto" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> If users use Unicode bidirectional control characters, the isolating RLI/LRI/FSI with PDI characters must be supported by the application and recommended (rather than RLE/LRE with PDF) by the spec. <a href="https://www.w3.org/TR/international-specs/#bidi_inline_rli" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Use of RLM/LRM should be appropriate, and expectations of what those controls can and cannot do should be clear in the spec. <a href="https://www.w3.org/TR/international-specs/#bidi_inline_rlm" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Detecting & matching direction (TBD)
